name: Lint

on: push

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run tests
        run: markdownlint .

  build-jekyll:
    - name: Pull
      uses: actions/checkout@v2
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - name: Build
      run: bundle exec jekyll build
